version: '3.8'

services:
  html:
    image: nginx
    depends_on:
      - service
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./.docker/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
  broker:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
    depends_on:
      - events
      - queues
  worker-blocks:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
    depends_on:
      - events
      - queues
  worker-price-pactfi:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
    depends_on:
      - events
      - queues
  worker-price-tinyman:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
    depends_on:
      - events
      - queues
  service:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
    depends_on:
      - events
      - queues

  # Outside Service Port Mappings
  events:
    image: redis:6.2
    ports:
      - "6380:6379"
    volumes:
      - ./.docker/config/redis.conf:/usr/local/etc/redis/redis.conf
      - events_vol:/data
  queues:
    image: redis:6.2
    ports:
      - "6381:6379"
    volumes:
      - ./.docker/config/redis.conf:/usr/local/etc/redis/redis.conf
      - queue_vol:/data
  couchdb:
    ports:
      - "5984:5984"

  # Tools
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - events
      - queues
    environment:
      - REDIS_HOSTS=events:events:6379,queues:queues:6379
    ports:
      - "8081:8081"
volumes:
  events_vol:
  queue_vol:
