version: '3.8'

services:
  # Local Volume Mapping
  broker:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
  worker:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
  worker-price-pactfi:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
  worker-price-tinyman:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
  service:
    volumes:
      - ./:/app
      - ./docker.env:/app/.env

  # Outside Service Port Mappings
  events:
    ports:
      - "6380:6379"
  queues:
    ports:
      - "6381:6379"
  couchdb:
    ports:
      - "5984:5984"

  # Tools
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - events
      - queues
    environment:
      - REDIS_HOSTS=events:events:6379,queues:queues:6379
    ports:
      - "8081:8081"
