version: '3.8'

services:
  html:
    image: nginx
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./.docker/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  broker:
    build: .
    entrypoint: npm
    depends_on:
      - events
      - queues
    environment:
      - APP_CONTEXT=broker
      - REDIS_ADDRESS=events
      - REDIS_MQ_ADDRESS=queues
      - ALGORAND_EXPLORER=https://testnet.algoexplorerapi.io
    command:
      - start
  worker:
    build: .
    entrypoint: npm
    environment:
      - APP_CONTEXT=worker
      - REDIS_ADDRESS=events
      - REDIS_MQ_ADDRESS=queues
      - COUCHDB_URL=http://admin:dex@couchdb:5984/dex
      - ALGORAND_EXPLORER=https://testnet.algoexplorerapi.io
    depends_on:
      - events
      - queues
    command:
      - start
  service:
    build: .
    entrypoint: npm
    depends_on:
      - events
      - queues
    environment:
      - APP_CONTEXT=socket
      - REDIS_ADDRESS=events
      - REDIS_MQ_ADDRESS=queues
      - ALGORAND_EXPLORER=https://testnet.algoexplorerapi.io
    command:
      - start
    ports:
      - "9001:9001"

#  algorand:
#    build:
#      context: .docker/algo
#    ports:
#      - "8080:8080"
#    volumes:
#      - algod:/root/node/data

  # Storage and Events
  events:
    image: redis:6.2
    volumes:
      - ./.docker/config/redis.conf:/usr/local/etc/redis/redis.conf
      - events_vol:/data
  queues:
    image: redis:6.2
    volumes:
      - ./.docker/config/redis.conf:/usr/local/etc/redis/redis.conf
      - queue_vol:/data
  couchdb:
    image: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=dex
    volumes:
      - couchdb_vol:/var/lib/couchdb
volumes:
  couchdb_vol:
  events_vol:
  queue_vol:
  algod: