name: '@algodex/service'
on:
  push:
    branches: [ main, development ]
  workflow_dispatch:
jobs:
  test:
    name: Test Codebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  release:
    needs: [test]
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v2
      # Setup Node and Publish
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
      - run: npm run semantic-release
        env:
          GIT_AUTHOR_NAME: PhearZero
          GIT_AUTHOR_EMAIL: git@phearzero.com
          GIT_COMMITTER_NAME: PhearZero
          GIT_COMMITTER_EMAIL: git@phearzero.com
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
